server:
  port: 8081

spring:
  application:
    name: api-finance-service-r
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true
